version: '3'

services:
 app: 
  build: .
  command: npm start
  ports: 
    - "3000:3000"
  volumes:
    - .:/usr/app
 mongodb:
  image: mongo:4.2.19
  ports:
    - "27017:27017"
  command: mongod --port 27017
  